#include<stdio.h>
#include<conio.h>

main()
{

   int n,A=1,B=2,C=3,D=4,E=5,F=6,G=7,H=8,I=9,J=10;


   clrscr();
   printf("Enter your nambar :\n");
   scanf("%d",&n);
   printf("%d*%d=%d\n",n,A,n*A);
   printf("%d*%d=%d\n",n,B,n*B);
   printf("%d*%d=%d\n",n,C,n*C);
   printf("%d*%d=%d\n",n,D,n*D);
   printf("%d*%d=%d\n",n,E,n*E);
   printf("%d*%d=%d\n",n,F,n*F);
   printf("%d*%d=%d\n",n,G,n*G);
   printf("%d*%d=%d\n",n,H,n*H);
   printf("%d*%d=%d\n",n,I,n*I);
   printf("%d*%d=%d\n",n,J,n*J);


   getch();


}